### ISSUE TITLE
Obtaining RV and stellar parameters from SDSS and LAMOST spectra using this package.

### ISSUE THREAD

**Issue by cxl4444** [segasai/rvspecfit#1]

**Comment by cxl4444** [comment]
Hello,

Does this program can calculate RV and stellar parameters from SDSS or LAMOST spectra during one observation consisted of multiple exposures?

Thank you!

**Comment by segasai** [comment]
Hi, 

The code can fit multiple exposures simultaneously. See the readme file on 'fitting severla spectra simultaneously'. If you provide the list of SpecData objects corresponding to different exposures it will include all of them in the fit.

**Comment by cxl4444** [comment]
> Hi,
> 
> The code can fit multiple exposures simultaneously. See the readme file on 'fitting severla spectra simultaneously'. If you provide the list of SpecData objects corresponding to different exposures it will include all of them in the fit.

Ok, thank you for your kindly reply and programs!

**Comment by cxl4444** [comment]
Hi,

When I run 'makeing the cross-correlation files' step (the last step), I got some troubles. 

These were the codes executed in my computer before the last step：
first step：
 rvs_read_grid --prefix /Users/cxl/PHOENIX/v2.0/HiResFITS/PHOENIX-ACES-AGSS-COND-2011/ --templdb files.db

second step:
vs_make_interpol --setup myconf --lambda0 4000 --lambda1 5000 \
    --resol_func '1000+2*x' --step 0.5 --templdb /Users/cxl/files.db \
    --oprefix /Users/cxl/phoenixconvertemp/ --templprefix /Users/cxl/PHOENIX/v2.0/HiResFITS/PHOENIX-ACES-AGSS-COND-2011/ --wavefile /Users/cxl/PHOENIX/v2.0/HiResFITS/WAVE_PHOENIX-ACES-AGSS-COND-2011.fits \
    --air --revision=v2020x

third step:
$ rvs_make_nd --prefix /Users/cxl/phoenixconvertemp/--setup myconf --revision=v2020x


This is the original code of the last step in the GitHub.
$ rvs_make_ccf --setup myconf --lambda0 4000 --lambda1 5000  \
    --every 30 --vsinis 0,10,300 --prefix ${PREFIX}/ --oprefix=${PREFIX} \
    --step 0.5 --revision=v2020x

This is the code executed in my computer.
rvs_make_ccf --setup myconf --lambda0 4000 --lambda1 5000  \
    --every 30 --vsinis 0,10,300 --prefix /Users/cxl/phoenixconvertemp/ --oprefix=${PREFIX} \
    --step 0.5 --revision=v2020x

 /Users/cxl/phoenixconvertemp/ is the file path of the n-d interpolator (the folder generated by previous step).

 --oprefix=${PREFIX}  do not change.

When I run above code, it was failed, and following was the output.
....
Processing : 4729 / 4734
Processing : 4730 / 4734
Processing : 4731 / 4734
Processing : 4732 / 4734
Processing : 4733 / 4734
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/bin/rvs_make_ccf", line 9, in <module>
    rvsccf.main(sys.argv[1:])
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/rvspecfit/make_ccf.py", line 517, in main
    ccf_executor(args.setup,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/rvspecfit/make_ccf.py", line 444, in ccf_executor
    with open(savefile, 'wb') as fp:
OSError: [Errno 30] Read-only file system: '/ccf_myconf.pkl'

Based on the output, I visit folders '/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/rvspecfit/' and '/opt/homebrew/Caskroom/miniforge/base/bin/', and  I do not find file ' /ccf_myconf.pkl'.

Does this file generate during the compile processes? 
Or do I need to put this file into the specified folder If I have this file? and if it is true, would you mind send a link where I can download this file.

Thank you very much!

**Comment by cxl4444** [comment]
Hello,

Your program has installed successfully, but when I fitted the spectrum which has wavelength range from ~3000 Angstrom to ~10000 Angstrom , the fitting process was failed. The code told me that the template library (3986.701794,5016.336633) doesn't cover this wavelength range (3803.644775,9219.342773).

Following are the fitting codes.
-------------------------------------------------------------------------------------
config=utils.read_config('/Users/cxl/phoenixconvertemp/config.yaml')

file=fits.open('/Users/cxl/Desktop/apitest/2738328623735088128_359.961198_1.127805/2738328623735088128_359.961198_1.127805_spec_0685_52203_0425.fits')

data = Table(file[1].data)

wavelength = 10**(data['loglam'])
flux = data['flux']
fluxerr = np.sqrt(1/data['ivar'])

sd = spec_fit.SpecData('myconf',lam=wavelength,spec=flux,espec=fluxerr)

res = fitter_ccf.fit([sd], config)
paramDict0 = res['best_par']
fixParam = [] 
if res['best_vsini'] is not None:
    paramDict0['vsini'] = res['best_vsini']

options = {'npoly':10}

res1 = vel_fit.process([sd],paramDict0,fixParam=fixParam,config=config,options=options)

print(res1)
-------------------------------------------------------------------------------------
Would you mind tell me what cause the error and show more examples about using your program?

Thank you very much!

Best regards!

**Comment by cxl4444** [comment]
Hello,

Your program has installed successfully, but when I fitted the spectrum which has wavelength range from ~3000 Angstrom to ~10000 Angstrom , the fitting process was failed. The code told me that the template library (3986.701794,5016.336633) doesn't cover this wavelength range (3803.644775,9219.342773).

Following are the fitting codes.
###################################################################################
config=utils.read_config('/Users/cxl/phoenixconvertemp/config.yaml')

file=fits.open('/Users/cxl/Desktop/apitest/2738328623735088128_359.961198_1.127805/2738328623735088128_359.961198_1.127805_spec_0685_52203_0425.fits')

data = Table(file[1].data)

wavelength = 10**(data['loglam'])
flux = data['flux']
fluxerr = np.sqrt(1/data['ivar'])

sd = spec_fit.SpecData('myconf',lam=wavelength,spec=flux,espec=fluxerr)

res = fitter_ccf.fit([sd], config)
paramDict0 = res['best_par']
fixParam = []
if res['best_vsini'] is not None:
paramDict0['vsini'] = res['best_vsini']

options = {'npoly':10}

res1 = vel_fit.process([sd],paramDict0,fixParam=fixParam,config=config,options=options)

print(res1)
###################################################################################

Would you mind tell me what cause the error and show more examples about using your program?

Thank you very much!

Best regards!

**Comment by cxl4444** [comment]
Hello,

Your program has installed successfully, but when I fitted the spectrum which has wavelength range from ~3000 Angstrom to ~10000 Angstrom , the fitting process was failed. The code told me that the template library (3986.701794,5016.336633) doesn't cover this wavelength range (3803.644775,9219.342773).

Following are the fitting codes.
###################################################################################
config=utils.read_config('/Users/cxl/phoenixconvertemp/config.yaml')

file=fits.open('/Users/cxl/Desktop/apitest/2738328623735088128_359.961198_1.127805/2738328623735088128_359.961198_1.127805_spec_0685_52203_0425.fits')

data = Table(file[1].data)

wavelength = 10**(data['loglam'])
flux = data['flux']
fluxerr = np.sqrt(1/data['ivar'])

sd = spec_fit.SpecData('myconf',lam=wavelength,spec=flux,espec=fluxerr)

res = fitter_ccf.fit([sd], config)
paramDict0 = res['best_par']
fixParam = []
if res['best_vsini'] is not None:
paramDict0['vsini'] = res['best_vsini']

options = {'npoly':10}

res1 = vel_fit.process([sd],paramDict0,fixParam=fixParam,config=config,options=options)

print(res1)
###################################################################################

Would you mind teach me how to deal with the error if I want to fit the whole spectrum, and show more examples about using your program?

Thank you very much!

Best regards!

**Comment by segasai** [comment]
When you create the library you need to specify the wavelength range --lambda0 --lambda1 options. Those need to cover the spectrum that you'll be fitting and also give some wiggle room due to different radial velocities  , i.e.  due to (1+dv/c) factor.
You just need to give a more generous wavelength range.

**Comment by cxl4444** [comment]
OK, I have done this, and it worked. You are so great!!!!! ^_^ ^_^ ^_^ ^_^

However, when I was fitting the spectrum, I met another problem.

I used a LAMOST spectrum with known stellar parameters to learn the fitting program, than I compared the fitting results to the stellar parameters provided by LAMOST, but the results are smaller than the LAMOST's. I think it is possibly due to the low resolution of the synthetic spectrum causing the inconsistency.

Than I find parameters that can be added into two functions spec_fit.SpecData() & vel_fit.process() during the fitting process, but I have no idea about what kind of data I need to add (thinks like a list? or other data types?), could you give me a dataset example about the resolution parameter?

Thank you very much! ^_^
